[CmdletBinding()]
param([string]$ConnectorRoot=$PSScriptRoot,[string]$HostsPath="$env:SystemRoot\System32\drivers\etc\hosts",[string]$StateRoot="$env:ProgramData\LocalRAG-ClientConnector",[switch]$Plan)
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop';$HostName='rag.home.arpa';$statePath=Join-Path $StateRoot 'state.json'
if(-not(Test-Path -LiteralPath $statePath)){if($Plan){[pscustomobject]@{AlreadyRemoved=$true;HostsPath=$HostsPath;StateRoot=$StateRoot}|ConvertTo-Json};return}
$state=Get-Content -LiteralPath $statePath -Raw|ConvertFrom-Json;$fields=@($state.PSObject.Properties.Name|Sort-Object);$required=@('block','certificate_sha256','certificate_subject','certificate_thumbprint','connector_generation','hosts_path','hosts_post_sha256','installation_id','prior_bytes_base64','prior_sha256','version')|Sort-Object
if(($fields-join ',')-cne($required-join ',') -or $state.version-ne 1 -or [string]$state.installation_id -cnotmatch '^[0-9a-f-]{36}$' -or [int]$state.connector_generation-lt 1 -or [string]$state.certificate_sha256-cnotmatch '^[0-9a-f]{64}$' -or [string]$state.certificate_thumbprint-cnotmatch '^[0-9A-Fa-f]{40}$' -or [string]$state.certificate_subject-cne 'CN=Local RAG Private CA'){throw 'Managed connector state schema is invalid.'}
if([string]$state.hosts_path -cne [IO.Path]::GetFullPath($HostsPath)){throw 'Managed hosts path does not match; refusing uninstall.'};$bytes=if(Test-Path -LiteralPath $HostsPath){[IO.File]::ReadAllBytes($HostsPath)}else{[byte[]]@()};$text=[Text.Encoding]::UTF8.GetString($bytes);$matches=[regex]::Matches($text,'# BEGIN LOCAL-RAG TEAM CONNECTOR.*?# END LOCAL-RAG TEAM CONNECTOR',[Text.RegularExpressions.RegexOptions]::Singleline);if($matches.Count-ne 1 -or ([regex]::Replace($matches[0].Value,'\r\n?',"`n") -cne [regex]::Replace([string]$state.block,'\r\n?',"`n"))){throw 'Managed hosts block drift detected; refusing uninstall.'}
$certs=@();$store=New-Object Security.Cryptography.X509Certificates.X509Store('Root','LocalMachine');$store.Open('ReadOnly');try{$certs=@($store.Certificates|?{$_.Thumbprint.ToUpperInvariant()-eq([string]$state.certificate_thumbprint).ToUpperInvariant()});if(@($certs|?{$_.Subject-cne [string]$state.certificate_subject}).Count-gt 0){throw 'Certificate drift detected; refusing removal.'}}finally{$store.Close()};$certPath=Join-Path $ConnectorRoot 'rag-local-ca.cer';if(Test-Path -LiteralPath $certPath){$sha=(Get-FileHash -LiteralPath $certPath -Algorithm SHA256).Hash.ToLowerInvariant();if($sha-cne[string]$state.certificate_sha256){throw 'Connector CA SHA-256 drift detected; refusing removal.'}}
if($Plan){[pscustomobject]@{HostsPath=$HostsPath;StateRoot=$StateRoot;CertificateThumbprint=([string]$state.certificate_thumbprint).ToUpperInvariant();CertificatePresent=($certs.Count-gt 0);Actions=@('remove exact managed hosts block while preserving unrelated edits','remove exact CA thumbprint')}|ConvertTo-Json -Depth 5;return}
if(-not([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)){throw 'Team connector removal must run elevated.'}
$newText=$text.Remove($matches[0].Index,$matches[0].Length);$tmp="$HostsPath.$([guid]::NewGuid().ToString('N')).tmp";[IO.File]::WriteAllText($tmp,$newText,[Text.UTF8Encoding]::new($false));Move-Item -LiteralPath $tmp -Destination $HostsPath -Force
if($certs.Count-gt 0){$store=New-Object Security.Cryptography.X509Certificates.X509Store('Root','LocalMachine');$store.Open('ReadWrite');try{foreach($c in $certs){if($c.Thumbprint.ToUpperInvariant()-ne([string]$state.certificate_thumbprint).ToUpperInvariant() -or $c.Subject-cne[string]$state.certificate_subject){throw 'Certificate drift detected; refusing removal.'};$store.Remove($c)}}finally{$store.Close()}};Remove-Item -LiteralPath $statePath -Force
